### ISSUE TITLE
http proxy options don't work on mac

### ISSUE THREAD

**Issue by joneian** [electron-userland/electron-download#73]
Version: electron-download@3.3.0

Further to https://github.com/electron-userland/electron-prebuilt/issues/21 the standard http_proxy environment variables work fine on windows and linux, but they don't seem to work on Mac. 

On Mac it doesn't work, but I can download the file manually using curl proving the proxy is working:
```
$ uname
Darwin
$ export HTTP_PROXY=http://fwdproxy:8080
$ export HTTPS_PROXY=http://fwdproxy:8080
$ ./node_modules/.bin/electron-download --version=1.7.9
Downloading tmp-65425-0-electron-v1.7.9-darwin-x64.zip
Error: tunneling socket could not be established, cause=connect ENETUNREACH 10.238.0.14:8080 - Local (0.0.0.0:57223)
/data/sandcastle/boxes/trunk-hg-fbobjc-fbsource/fbobjc/Apps/workplace-desktop/node_modules/electron-download-tf/lib/cli.js:15
  if (err) throw err
           ^

Error: tunneling socket could not be established, cause=connect ENETUNREACH 10.238.0.14:8080 - Local (0.0.0.0:57223)
    at ClientRequest.onError (/data/sandcastle/boxes/trunk-hg-fbobjc-fbsource/fbobjc/Apps/workplace-desktop/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
$ curl -L -p -x http://fwdproxy:8080 --create-dirs -o $HOME/Library/Caches/electron/electron-v1.7.9-darwin-x64.zip https://github.com/electron/electron/releases/download/v1.7.9/electron-v1.7.9-darwin-x64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   619    0   619    0     0   1479      0 --:--:-- --:--:-- --:--:--  1480
100 46.1M  100 46.1M    0     0  18.5M      0  0:00:02  0:00:02 --:--:-- 25.0M
```
On Linux in the same environment it works fine:
```
$ uname
Linux
$ export HTTP_PROXY=http://fwdproxy:8080
$ export HTTPS_PROXY=http://fwdproxy:8080
$ ./node_modules/.bin/electron-download --version=1.7.9
Downloading tmp-998848-0-electron-v1.7.9-linux-x64.zip
[============================================>] 100.0% of 51.24 MB (13.66 MB/s)
Downloaded zip: /home/ianj/.cache/electron/electron-v1.7.9-linux-x64.zip
```

**Comment by MarshallOfSound** [comment]
Closing this out as the downloader logic was rewritten as part of `next`
